spring:
  main:
    banner-mode: off

  application:
    name: "library-management-system"
  datasource:
    url: jdbc:postgresql://localhost:5432/library_system
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8080
logging:
  level:
    root: info
